name: Install yt-dlp and Deploy Bot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_yt_dlp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Set Python version to install yt-dlp

      - name: Install yt-dlp via pip
        run: |
          python -m pip install -U yt-dlp  # Install yt-dlp using pip

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install  # Install Node.js dependencies

      - name: Start the bot
        run: npm start  # Start the bot after everything is installed
