name: Install yt-dlp and Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  install_yt_dlp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          npm install

      - name: Install yt-dlp using apt-get
        run: |
          sudo apt-get update
          sudo apt-get install -y yt-dlp

      - name: Deploy to Render
        run: |
          echo "Deploying to Render" # Isme apna Render deployment command daal sakte hain.
