name: Install yt-dlp and Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  install_yt_dlp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install yt-dlp
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp

      - name: Install dependencies
        run: |
          npm install

      - name: Deploy to Render
        run: |
          echo "Deploying to Render"  # Add your Render deployment command here
